#!/bin/sh
NAME=xpra-standalone
docker stop $NAME
docker rm $NAME
docker build -t wuebbel/$NAME .
docker run -h $NAME \
	-d \
	--name $NAME \
	-p 14502:14500 \
	wuebbel/$NAME
#docker exec -t -i $NAME /bin/bash --login
sleep 2
firefox localhost:14502
